name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Docker
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
    - name: Build the Docker image
      run: docker build -t saiaswinmadhavan/empapp:v1 ./src
    - name: Push the Docker image
      run: docker push saiaswinmadhavan/empapp:v1